# Generated by Django 5.1.2 on 2024-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='admission_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
        ),
    ]
